URL_GSHEET_API = "https://script.google.com/macros/s/AKfycbwQQ_zsrYSh31UMf6bDboHEnt3ao5YH-aVKqHnw3uARGD3U0m0EwDgMg5D7rHpLfS71eA/exec"
TELEGRAM_BOT_TOKEN = "8936505684:AAGM3KuPnq8u88Y3HMDKmvBHkQuthsq9bwI"
TELEGRAM_CHAT_ID = "2106196278"
