URL_GSHEET_API = "https://script.google.com/macros/s/AKfycbwHQECxg9gCnamFsE_YbKQcqrYsN8EKtpTDGm8XYsoD-m31xUOmASPuxOil7iCoyxqZwA/exec"
TELEGRAM_BOT_TOKEN = "8936505684:AAGM3KuPnq8u88Y3HMDKmvBHkQuthsq9bwI"
TELEGRAM_CHAT_ID = "2106196278"
